### ISSUE TITLE
XP title

### ISSUE THREAD

**Issue by tla-dev** [k3b/APhotoManager#104]
Editing exif data on a picture adds an exif XPtitle for the title and an exif XPComment for the description.

XP tags are microsoft windows tags.

Would it be better to edit the exif title and the exif description instead? It would be better interoperability with other softwares like digikam.

As workaround I use exiftool to copy the XPtitle to the exif description:
`exiftool "-Description<xptitle" *.jpg`

**Comment by k3b** [comment]
Thanks for feedback.

The mapping is documented in https://github.com/k3b/APhotoManager/wiki/Metadata. For title that is

* Title 	ExternalXmp.Title 	Exif.XPTITLE 	IptcDirectory.TAG_HEADLINE 	InternalXmp.Title 		

The write strategy is to write the title to every field that has the meaning of title while read strategy is to use first matching one.

Unfortunately there is no exif-title (or i am not aware of) that is why microsoft invented Exif.XPTITLE . title belongs to IptcDirectory.TAG_HEADLINE which my app (or the lib it uses) can read but not write.

XPTITLE is the only way i have found so far to embed a title into the jpg. 

in your example 

      exiftool "-Description<xptitle" *.jpg

is interpreted as something similar to

     exiftool "-xmp:Description<exif:xptitle" *.jpg

If you have an idea how to solve this (without embedding exiftools in my android-app) let me know.

I have found no way yet (or lib) to write iptc or embedded-xmp into the jpg
