### ISSUE TITLE
Mode App protected/pinned: Feature idea: read-only when pinned

### ISSUE THREAD

**Issue by hcgraf** [k3b/APhotoManager#105]
Hi,

I'm looking for a gallery app that locks any write access when pinned (for pinning, see e.g. here: https://www.addictivetips.com/android/pin-and-unpin-screens-in-android-lollipop/)

It's basically to give the gallery to children or "technically-unaware" people without any risk.
When pinned, the app should basically prevent:
* Deletion
* Any persistent modification
* Sharing
* Changing settings

Do you think that's possible (I'm unsure if pinning can be detected)? 
Would that be a reasonable feature for this app?

Thanks
Hagen

**Comment by k3b** [comment]
A great idea.

I will implement this together with #100: while the global search filter is password protected, write operatons (edit-exif/delete/copy/send/...) will be disabled within the app, too.

do not expect this feature within the next two months. I am quite busy at job and currently there is a lot of refactoring neccessary to finish Autoprocessing # 93

**Comment by k3b** [comment]
will be available with next version 0.6.3

**Comment by hcgraf** [comment]
Cool, thanks a lot! I'll test it as soon as possible!

**Comment by k3b** [comment]
@hcgraf : betta is available here https://github.com/k3b/APhotoManager/releases/tag/Betta105.1-0.6.3
