### ISSUE TITLE
App Crashes While click on the settings option. 

### ISSUE THREAD

**Issue by wanizubair** [k3b/APhotoManager#116]
#### Expected behavior
The App should be able to open the settings. 

#### Actual behavior
When we click on settings option app Crashes and we are not able to open the settings. 

#### How to reproduce

+ Launch the app. 

+ Click on the menu at the top of the right corner of the app you see different options there. 

+ Click on settings, app Crashes and you are not able to open the settings. 

* Application : A Photo Manager. Version :0.6.4.180314
* Operating system: Android Nought (7.0)

#### Recording Of The Bug

https://youtu.be/T5hKhGOzV4A    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@wanizubair/app-crashes-while-click-on-the-settings-option">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by k3b** [comment]
... fixing problem...

**Comment by k3b** [comment]
Fixed in next f-droid hotfix release v0.6.4.180321

**Comment by k3b** [comment]
Soved in bugfix release
