### ISSUE TITLE
A photo manager crashes on opening filemanager(clicking folder icon) and rotating the screen

### ISSUE THREAD

**Issue by neupanedipen** [k3b/APhotoManager#119]
#### Expected behavior
After opening the app and clicking on the file icon from top bar of the app and rotating the screen to view in landscape mode, the interface should rotate with the screen.<br>

#### Actual behavior
But when you click on the folder icon to open file manager from the app and rotate the screen the app crashes and stops.<br>

#### How to reproduce
1. Download A Photo Manager from [F-Droid](https://f-droid.org/packages/de.k3b.android.androFotoFinder/), install it and launch it.<br>
2. Click on the folder icon as shown in the following screenshot.<br>![](https://s19.postimg.org/qg2prl9ib/20180403_194919.png)
3. Switch the orientation of your screen to landscape mode and Rotate the screen of your phone.<br>
The app now will crash and stop and will show a message as below.<br>![](https://s19.postimg.org/abqvc27gz/20180401_162213.png)
This bug is reported in Samsung Galaxy J5 Android 6.0.1 and A Photo Manager app version 0.6.4.180321. <br>
* App Version: 0.6.4.180321 <br>
* Operating system: Android 6.0.1

#### Recording Of The Bug
Here's the bug recorded in video.<br>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/cArA3fUzC0Q" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@neupanedipen/a-photo-manager-crashes-on-opening-filemanager-and-rotating-the-screen">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by k3b** [comment]
I confirm, the problem is reproducable.

Thankyou for telling me.

**Comment by k3b** [comment]
done. bugfix will be available with next release 0.7.0
