### ISSUE TITLE
[FR] rotate 90° / orientation tag

### ISSUE THREAD

**Issue by ildar** [k3b/APhotoManager#129]
the app is editing EXIF but doesn't handle the most used tag: Orientation.
Please implement lossless rotation 90°/180°/270° through EXIF. As an UI example see Shotwell application.
Thanks

* Affected Module:
	* [x] [Image-View](https://github.com/k3b/APhotoManager/wiki/Image-View)

**Comment by ildar** [comment]
I am sorry, I don't see how user can change image gravity/orientation.
Please explain or reopen.

**Comment by k3b** [comment]
Sorry my fault: i did not read the complete question. 

I only fixed display in wrong orienentation when orientation flag was set.

but not implemented activly-modify the orientation in the exif from the gui = edit

**Comment by ildar** [comment]
Please reopen

**Comment by supercub** [comment]
Hi, i'm using "A Photo Manager (Version AndroFotoFinder 0.7.5.190916)"  and even if orientation flag is set in a picture, it isn't rotated automatically. The [EXIFTOOL](https://github.com/exiftool) output of this picture is 'Orientation: Rotate 90 CW'.

**Comment by ildar** [comment]
1st, thanks for fixing one bug.
But I am sorry, the same again )))
https://github.com/k3b/APhotoManager/issues/129#issuecomment-487521275
> I don't see how user can change image gravity/orientation. Please explain
or reopen.

**Comment by supercub** [comment]
Hi k3b, thanks for fixing the bug. In version 0.8.0 pics are now rotated automatically according to their EXIF orientation flag.

**Comment by k3b** [comment]
@supercub thanks for feedbak

**Comment by k3b** [comment]
@ildar i have created a new ticket for "command to rotate image" in #154

**Comment by ildar** [comment]
ok, thanks.

**Comment by k3b** [comment]
the next llcrop version will support image rotation https://github.com/k3b/LosslessJpgCrop/ . you can call it a a photo editor from a photo manager.
