### ISSUE TITLE
Option to change EXIF rating direct in Image-View

### ISSUE THREAD

**Issue by StefanOltmann** [k3b/APhotoManager#130]
**Is your feature request related to a problem? Please describe.**
As a user of both Canon DPP and digiKam I'm used to see the five star rating bar together with the photo and not in a seperate view. This Info is he most imporant one to me for choosing the best photos. 

**Describe the solution you'd like**
There should be a five star rating bar on buttom of the Image-View.
Maybe this should be a setting if someone is not interested in the rating.

**Describe alternatives you've considered**
Have the setting bar in a split pane for tablets.

**Additional context**
None.

* Affected Module:
	* [ ] [Gallery-View](https://github.com/k3b/APhotoManager/wiki/Gallery-View)
	* [ ] [Geographic-Map](https://github.com/k3b/APhotoManager/wiki/geographic-map)
	* [X] [Image-View](https://github.com/k3b/APhotoManager/wiki/Image-View)
	* [ ] [Filtering](https://github.com/k3b/APhotoManager/wiki/Filter-View)
	* [ ] [Folder-Picker](https://github.com/k3b/APhotoManager/wiki/Folder-Picker)
	* [ ] [Settings](https://github.com/k3b/APhotoManager/wiki/settings)
	* [ ] [Intent API](https://github.com/k3b/APhotoManager/wiki/intentapi)

**Comment by k3b** [comment]
Thankyou for this ticket.

The same issue applys to all meta data:

* gps
* filename
* title
* description
* tags
* date
* and also in (de-)select in multiselection

If you only want to see the stars:

Current implementation already remebers last action (exif edit, remname, ....) to offer a quick button for this. Example: After the first exif-edit in image detail view you should see a text overlay which also shows the rating as stars in the last line. This quick-mode is lost if you leave the image detail view.

I like the idea of split-view for tablets....

**Comment by StefanOltmann** [comment]
Thank you for your reply.

What so you mean by current implementation? In the latent release 0.7.1 I so not see that feature. Only a pencil icon that takes me back to the other screen.

**Comment by k3b** [comment]
Sorry i just realised that this is an undocumented config issue.

* goto imagedetailsview. In menu select "more.../load Context..."
* long-press on any entry opens a texteditor where display formulas for text-ovelay 
* i assume that this will create the default text-overlay settings. i will check it tomorrow afternoon

**Comment by k3b** [comment]
the disply only feature was implemented here: https://github.com/k3b/APhotoManager/issues/70 does this solve your problem? can we close this ticket?

**Comment by StefanOltmann** [comment]
I don't see how this gives me a five star rating bar directly in the Image-View.

long-press on an item in the "more.../load context..." menu crashes the app for me.

But you can close the ticket anyway as I decided to use another app.
