### ISSUE TITLE
Crash when mapping, only shows subset of photos in manager

### ISSUE THREAD

**Issue by ithink314** [k3b/APhotoManager#134]
**Describe the bug**
Mapping crashes. Only 24 photo thumbnails are shown in A Photo Manager list, even after scanning media or subset of media, and seeing message about files found.

**To Reproduce**
Click on A Photo Map icon or select "Map Area Filter" in A Photo Manager. Crashes.
Click on A Photo Manger. Only 24 photo  are shown, of thousands. 

**Expected behavior**
Show all photos in list and on map like it did previously.

**Smartphone (please complete the following information):**
 - Android version [e.g. Android-7.1] :
Android 8.1.0, microg lineage 15.1-20190123-microG-shamu, on Nexus 6 without Gapps.

 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :
0.7.2.181027 from f-droid.

**Additional context**
First saw the crashes with OSMAnd version 3.2.7, updated 12/5/18, but downgrade to version 3.2.6 did not help.
Recently started using some v5 Mapsforge offline maps, and some are stored with modified names (duplicate US states at v3 or v5).

[androFotofinder.logcat-20190129-154055.txt](https://github.com/k3b/APhotoManager/files/2808561/androFotofinder.logcat-20190129-154055.txt)

**Crash Report**
Attached example.

When APhotoManager crashes it tries to write a crash log file in the [**Error Log Folder**](https://github.com/k3b/APhotoManager/wiki/settings#logfolder).

* [ExternalStorageDirectory]/copy/log/androFotofinder.logcat-2017....txt
  * i.e. /storage/sdcard0/copy/log/androFotofinder.logcat-20170728-135704.txt
    * crash data from 2017-07-28 13:57
    
For more details on Error Loging see [diagnostic settings](https://github.com/k3b/APhotoManager/wiki/settings#Diagnostics).

**Comment by ithink314** [comment]
After clicking Menu, Filter, and checking Private Image and With No Tags boxes (Public image was already checked), and clicking check mark at top, it now displays thousands of thumbnails in list as expected.  "Private Image" and "With no Tags" are now unchecked again without me doing it. There is a chance a background scan process happened to finish about the same time but that seems unlikely coincidence.

Mapping still crashes.

**Comment by k3b** [comment]
thanks for the report:

form error log

		[ 01-29 10:40:38.756  8974: 8974 E/k3bFoto  ]
		LogCat.uncaughtException org.mapsforge.map.reader.header.MapFileException: unsupported file version: 5
		org.mapsforge.map.reader.header.MapFileException: unsupported file version: 5

you are using mapsforge offline maps that are not compatible with current APhotoManager version.

I am currently using 2 years old data so i assume that the mapsforge fileformat has changed.

If you either disable offline maps or download old-format-map-filess you should be able to use the maps again.

I need to update a-photo-manager-app to latest mapsforge-libraries

**Comment by k3b** [comment]
Should be fixed with #135
