### ISSUE TITLE
Q: how to "move" tag across hierarchy?

### ISSUE THREAD

**Issue by xandro0777** [k3b/APhotoManager#138]
I have the tag "Unsorted/Peter"  and would like to move it to "People/Peter".  Is that possible? How? I know how to move it one level down but not to different "Directory".. would ".." work?

**Comment by k3b** [comment]
You can modify the tag directory tree through the clipboard: Cut "Peter" from "Unsorted/Peter" and paste it to "People" will result in "People/Peter"

To move "/Unsorted/People" to "Unsorted/People" rename "People" to "/People"

Unfortunately the tag management currently does not support "." or ".."

If this answeres your question please close the ticket

**Comment by xandro0777** [comment]
> You can modify the tag directory tree through the clipboard: Cut "Peter" from "Unsorted/Peter" and paste it to "People" will result in "People/Peter"
> 
> To move "/Unsorted/People" to "Unsorted/People" rename "People" to "/People"

this works.. although by accident I ended up with one Tag in 2 places in the hierarchy. This raises my  next question - does the hierarchy have any functional meaning or is it just there to have the tags grouped visualy? I tried things like filtering for "People" and expected it would match all subtags but this didn't seem to work? The only bit of explanation I found in the docs was ```Example: If you long tap on bookmark "/_demo/holiday/habour" then the tags "_demo", "holiday" and "habour" are bookmarked.``` in https://github.com/k3b/APhotoManager/wiki/Tags - however don't see how this would work.

**Comment by k3b** [comment]
> does the hierarchy have any functional meaning

yes reduce the number of tag searches if you have more tags that fit on on screen. Example : 

* i want to a tags to the selected image(s)
* search for "peter" 
* i find "/people/family/peter"
* I long-tap on this entry to add "people", "family" and "peter" to selected tags (without the need to search for "people" and "family".
* => one search gets three tags

This way all my photos that contain known people gets the tag "people" so that i can easyly hide them in the global base-filter "exclude all photos that have tag=people"

**Comment by xandro0777** [comment]
it seems what confused me was that tagging a picture with "peter" did not also automagically tag the image with "people" so obviously filtering for people couldn't show any results.

**Comment by k3b** [comment]
> ... what confused me ...

ok i understand. 

I agree the current tag-gui is the opposite of intuitive and need a big redesign :-( 

Unfortunately the coding part of this app is a one man hobby project and i do not have the time to fix all issues/features

**Comment by xandro0777** [comment]
No problem, with all those little difficulties it is still the best app around and as of GUIs I am not at all talented using them so it may be my fault. 

Once I get a better grasp of it I would try to improve the documentation.
