### ISSUE TITLE
Background color: black? (Up to now it is white)

### ISSUE THREAD

**Issue by guettli** [k3b/APhotoManager#14]
Most image apps use a black background when images get displayed in fullscreen.

I would prefer black, too.

What do you think?

Why did you choose white?

**Comment by MaxLanar** [comment]
I support this request ! :) The possibility to configure that would be great...

**Comment by k3b** [comment]
On my side this ticket has a very low priority because i have outer things in the queue for this hobby project with much higher priority.

May be there is somebody else out there who fixes this: 

**Todo**

* Find out how to set the background color in chris bane's PhotoView (https://github.com/chrisbanes/PhotoView)
* Implement a config - gui (Currently 2015-10-05) the is no config gui
  * The properties that could go into a config-dialog are all at 
    * [app/src/main/java/de/k3b/android/androFotoFinder/Global.java](https://github.com/k3b/AndroFotoFinder/blob/FDroid/app/src/main/java/de/k3b/android/GuiUtil.java)

**Comment by Tuuux** [comment]
Hello everyone

I really recommend to have a capability to have a Dark Skin and Light Skin, that because Dark Skin will save Battery and that good for everyone. A low energy App is more GreenIT.
For me go to that direction should permit Dark Background.

Then 100% support that feature request ...

**Comment by keunes** [comment]
> because Dark Skin will save Battery and that good for everyone. A low energy App is more GreenIT. [@Tuuux]

Only for devices with amoled screens, for any of the other screens: no difference.

> On my side this ticket has a very low priority because i have outer things in the queue for this hobby project with much higher priority. [@k3b]

I get it. Yet like the OP I would just prefer a black background over a white one. Then colour-picking (I would not only have black & white, but also grey) can be added later as an enhancement.

**Comment by k3b** [comment]
If you find a way to implement backgroundcolor to the PhotoView please send me a merge request to

* https://github.com/k3b/PhotoView

Unfortunately the [original master branch of chrisbanes-PhotoView](https://github.com/chrisbanes/PhotoView) did  not accept the improvements i made for APhotoManager [here](https://github.com/chrisbanes/PhotoView/pull/373) and [here](https://github.com/chrisbanes/PhotoView/pull/387)  so i keep my own fork

**Comment by markusb** [comment]
Just came here for the background color. I do have quite a few pictures with a dark theme and they are pretty ugly with the white background. But there are some clear pictures too, where a bighter background would be appropriate.

I this the best option is similar to the Philips TV ambilight, where the background adapts to the picture.

While looking at the Photoview app here https://github.com/chrisbanes/PhotoView/issues/201 I came across this snippet:

    <<uk.co.senab.photoview.PhotoView
    android:id="@+id/imgView"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="@color/transparent"
    android:src="@drawable/image"
    />

This sounds to me to be the way to choose the background color. I may be completely off, though.

**Comment by k3b** [comment]
blocked: this should wait until #70 implementatino is finished:

Image display is refactored from manuel new PhotoView() to layoutfile

**Comment by k3b** [comment]
done with #162
