### ISSUE TITLE
Photo Manager will not open email (K-9 Mail) attached images.

### ISSUE THREAD

**Issue by Rbagman** [k3b/APhotoManager#141]
When I select Photo Manager to view an email attachment it loads the same stock image that came preloaded on my device.

I am unable to navigate or change the image being viewed, only edit and share that image. Ghost Commander Image viewer works as expected when selected.

My device is rooted Samsung GT-N7100/Android 4.4.2.

**Comment by k3b** [comment]
Thanks for the report. 

Can you add error-log infos as described in https://github.com/k3b/APhotoManager/wiki/Problem-Reporting-Logfile-Howto  ?

**Comment by k3b** [comment]
@Rbagman : Thanks for the report.

I need to know a non-working example- intent  (action, url, mime) where a photo manager fails

You can get this example infor from error-log infos as described in https://github.com/k3b/APhotoManager/wiki/Problem-Reporting-Logfile-Howto

**Comment by k3b** [comment]
@Rbagman : i cannot fix it without the info from error log

I need to know a non-working example- intent (action, url, mime) where a photo manager fails from the log.

Feel free to reopen the ticket when error log is available.
