### ISSUE TITLE
AsyncTask rembering owning Activity may cause memory leak

### ISSUE THREAD

**Issue by pangeneral** [k3b/APhotoManager#145]
According to our research, there are misuses about the following two AsyncTask classes:
1. `de.k3b.android.widget.AsyncTaskWithProgressDialog`
2. `de.k3b.android.androFotoFinder.directory.DirectoryLoaderTask`

The problems are:
1. They hold strong reference to the GUI element of Activity, which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish
2. Their instances are not cancelled before the Activity is destroyed, which can lead to the wrong invocation of onPostExecute

I think we can make following changes to fix the misuse problems:
1. I think the GUI-related fields should be wrapped into WeakReference. Take `protected Activity parent` as example, it can be changed tp `private final WeakReference<Activity> parent`.
2. Add a AsyncTask field in the corresponding Activities which use AsyncTask. These fields refer to the annoymous AsyncTask objects. Then invoke `cancel()` in the onDestroy() method of Activities.

These are my suggestions above, thank you.

**Comment by k3b** [comment]
Thanks for feedback.

I have just read https://stackoverflow.com/questions/18297378/weakreference-asynctask-pattern-in-android.

My changes: 

* de.k3b.android.androFotoFinder.directory.DirectoryLoaderTask now remembers activity.getApplicationContext() which is valid as long as app is living.
* de.k3b.android.widget.AsyncTaskWithProgressDialog : changed implementation to WeakReference

Do you think that this is enough to solve the potential issue?

if yes this will be fixed with next release

**Comment by pangeneral** [comment]
> Thanks for feedback.
> 
> I have just read https://stackoverflow.com/questions/18297378/weakreference-asynctask-pattern-in-android.
> 
> My changes:
> 
> * de.k3b.android.androFotoFinder.directory.DirectoryLoaderTask now remembers activity.getApplicationContext() which is valid as long as app is living.
> * de.k3b.android.widget.AsyncTaskWithProgressDialog : changed implementation to WeakReference
> 
> Do you think that this is enough to solve the potential issue?
> 
> if yes this will be fixed with next release

I think it partially solve this problem. A better solution is `cancel` the instance of AsyncTask when Activity is destroyed such that `onCancelled()` instead of `onPostExecute()` will be invoked. Currently, the memory leak has been solved. However, there are still potential danger of errors caused by wrong invocation of `onPostExecute()`. 
That's my personal advice above. I hope it's useful for you :)
