### ISSUE TITLE
On LG V30 orientation display wrong

### ISSUE THREAD

**Issue by mutaunt** [k3b/APhotoManager#148]
Although the thumbnails are correctly oriented when I select a photo to view its orientation is wrong.  90 anticlockwise for portrait, 180 degrees for landscape.  This is easy to repeat, it always happens for all photos taken with LG camera software.

Notes:
Clearing app data did nothing
Same issue happens on Android 8 & 9
Happens with all recent versions tried including latest 0.7.5.190916
No other gallery type of app I've used has this issue
Google search found no references to LG camera orientation issues. 
Photos taken with Open Camera are shown with correct orientation suggesting APhotoManager can't parse the LG tag info correctly???

**Comment by k3b** [comment]
The issue should be fixed with version 0.8 which i just released
