### ISSUE TITLE
crash when the Map Area Filter is entered, click ok button and the round button at the same time.

### ISSUE THREAD

**Issue by DkiJing** [k3b/APhotoManager#157]
**Describe the bug**
The app crash when the Map Area Filter is entered, I click ok button and the round button at the same time.  

**To Reproduce**

1. Click setting button
2. Click on 'Map Area Filter'
3. Click OK button and drag the ball button at the same time

**Actual behavior**
The app crash, and return to the phone main interface

**Smartphone (please complete the following information):**
 - Device: HUAWEI P9
 - Android version [e.g. Android-7.1] : Android 8.0
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) : 0.7.5.190916

**Comment by DkiJing** [comment]
This bug is found by monkey test. It's a kind of extreme case.

**Comment by k3b** [comment]
The bug is reproducable.

I will fix it when the android-10-compatibility issues are fixed

**Comment by k3b** [comment]
done
