### ISSUE TITLE
images in folders

### ISSUE THREAD

**Issue by DoctorSubtilis** [k3b/APhotoManager#160]
**Is your feature request related to a problem? Please describe.**
This is the first (and so far the only) app I have found with _all the images_ in the same "container", _all together_: why you don't give the possibility to see images in their folders (i.e. "camera", "instagram", "whastapp" and the like)?

**Describe the solution you'd like**
A new type of visualization of photos, distinct by their (physical) folder

* Affected Module:
	* [X] [Gallery-View](https://github.com/k3b/APhotoManager/wiki/Gallery-View)
	* [X] [Folder-Picker](https://github.com/k3b/APhotoManager/wiki/Folder-Picker)
	* [ ] [Settings](https://github.com/k3b/APhotoManager/wiki/settings)
	* [ ] [Intent API](https://github.com/k3b/APhotoManager/wiki/intentapi)

Thanks!

**Comment by k3b** [comment]
If you click on the folder picker you can see all folders/albums that have images inside. If you click on that folder you only get images that are insinde and below of this folder.

Does this answer your qestion?

If not: can you describe the question in more details?
