### ISSUE TITLE
Performing pause of activity that is not resumed

### ISSUE THREAD

**Issue by anlalalu** [k3b/APhotoManager#163]
###### Stack Trace

E/ActivityThread( 9156): Performing pause of activity that is not resumed: {de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}
E/ActivityThread( 9156): java.lang.RuntimeException: Performing pause of activity that is not resumed: {de.k3b.android.androFotoFinder/de.k3b.android.androFotoFinder.FotoGalleryActivity}
E/ActivityThread( 9156): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3015)
E/ActivityThread( 9156): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3003)
E/ActivityThread( 9156): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2981)
E/ActivityThread( 9156): 	at android.app.ActivityThread.access$1000(ActivityThread.java:135)
E/ActivityThread( 9156): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
E/ActivityThread( 9156): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 9156): 	at android.os.Looper.loop(Looper.java:136)
E/ActivityThread( 9156): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/ActivityThread( 9156): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread( 9156): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread( 9156): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/ActivityThread( 9156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/ActivityThread( 9156): 	at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = v0.8.0.191021

Android Version = 7.1.0

**Comment by k3b** [comment]
Thanks for the info. 

I have no clueue how this could happen
