### ISSUE TITLE
F-Droid Summary

### ISSUE THREAD

**Issue by uniqx** [k3b/APhotoManager#165]
F-Droid will update how we display summary text in our next app release. Summary text will now always be highlighted and prepended to the long app description.

Your long description text starts with the same text you've got in your summary text. This will look redundant. I recommend to remove the summary text from your long description.

here are more infos/screenshots about this update: [fdroidclient!855](https://gitlab.com/fdroid/fdroidclient/merge_requests/855)

**Comment by k3b** [comment]
@uniqx thanks for the info.

Does the fdroidclient change require a new release of my app to take affect or will it pull the current github-app description ?

**Comment by uniqx** [comment]
You do not need to do a release for that.

**Comment by k3b** [comment]
ok. thanks. I will do this tonight, when i am home

**Comment by k3b** [comment]
done. summy is now available in branches f-droid and master
