### ISSUE TITLE
open and manage photo from my folder ftp

### ISSUE THREAD

**Issue by lucassssmi** [k3b/APhotoManager#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

* Affected Module:
	* [ ] [Gallery-View](https://github.com/k3b/APhotoManager/wiki/Gallery-View)
	* [ ] [Geographic-Map](https://github.com/k3b/APhotoManager/wiki/geographic-map)
	* [ ] [Image-View](https://github.com/k3b/APhotoManager/wiki/Image-View)
	* [ ] [Filtering](https://github.com/k3b/APhotoManager/wiki/Filter-View)
	* [ ] [Folder-Picker](https://github.com/k3b/APhotoManager/wiki/Folder-Picker)
	* [ ] [Settings](https://github.com/k3b/APhotoManager/wiki/settings)
	* [ ] [Intent API](https://github.com/k3b/APhotoManager/wiki/intentapi)

Hi guys, it's a new idea to view and manger my photos thats are in ftp folder ?
My photo.google its' full and would like to see and edit my photos.
Thank for your reply.

**Comment by lucassssmi** [comment]
i am sorry,
example i have create my gallery on my ftp web server by code php, like this module https://www.ubergallery.net/
Now i can see my photos by url and ftp.. i would like to see that by aphotomanger..
Lucas.

**Comment by vinceh121** [comment]
So in short you want FTP support?

**Comment by lucassssmi** [comment]
Yes, or php web server ..
Thanks

**Comment by k3b** [comment]
sorry, the app is for local photos only. Searching for online photos would require to download them all and put the search infos into a local database wich would be a performance nightmare.

Use a server side gallery app instead.
