### ISSUE TITLE
[CRASH] on removing an image

### ISSUE THREAD

**Issue by ildar** [k3b/APhotoManager#167]
**Describe the bug**
delete image [inside Image-Detail-View] leads to immediate crash. It wasn't so before upgrade to 0.8.1.200212

**Smartphone (please complete the following information):**
 - Android version : Android-7.1
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) : 0.8.1.200212 F-Droid

**Crash Report**
[androFotofinder.logcat-20200217-045724.txt](https://github.com/k3b/APhotoManager/files/4211931/androFotofinder.logcat-20200217-045724.txt)

**Comment by k3b** [comment]
Fixed in v0.8.1.200218 (46)  which i just realeased

**Comment by k3b** [comment]
fixed in last release
