### ISSUE TITLE
APhotoManager is broken (cannot load pictures) on Android 6.0/Android7.1 emulators

### ISSUE THREAD

**Issue by tingsu** [k3b/APhotoManager#177]
**Describe the bug**

I installed the latest apk version on the market. When I open the app and click the folder icon on the top tool bar, the app just shows a toast warning "loading folder Folder failed". But when I use this app on a real device (Android 9.0). The app can load the images.  So, APhotoManager does not support Android emulators?

**To Reproduce**
1. Start the app
2. click the current folder icon on the top tool bar

**Expected behavior**

The app should be able to load the images 

**Smartphone (please complete the following information):**
 - Android version [e.g. Android-7.1] :
 - [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :

Android 6.0 / Android 7.1, both have this issue.
APhotoManager 0.8.3.200315

**Additional context**

![Selection_305](https://user-images.githubusercontent.com/3156978/86453255-c67cf280-bd1d-11ea-8de3-5cc733bd3af9.png)

**Crash Report**
If you report an app crash: Can you add the crash logfile to this ticket?

No Crash

When APhotoManager crashes it tries to write a crash log file in the [**Error Log Folder**](https://github.com/k3b/APhotoManager/wiki/settings#logfolder).

* [ExternalStorageDirectory]/copy/log/androFotofinder.logcat-2017....txt
  * i.e. /storage/sdcard0/copy/log/androFotofinder.logcat-20170728-135704.txt
    * crash data from 2017-07-28 13:57
    
For more details on Error Loging see [diagnostic settings](https://github.com/k3b/APhotoManager/wiki/settings#Diagnostics).

**Comment by k3b** [comment]
since the emulator does not work on my computer i need your help to find out more:

> Crash Report
> If you report an app crash: Can you add the crash logfile to this ticket?
>   No Crash

In the settings dialog near the the buttom there is "save logcat to file". can you press this  to manually generate a logfile and attach it to the ticket?

Do you have photos on the emulator? do other gallery apps show photos on the emulator?

**Comment by k3b** [comment]
closed as there was no answer after 4 years
