### ISSUE TITLE
Tiny survey about energy aware software practices.

### ISSUE THREAD

**Issue by moraispgsi** [k3b/APhotoManager#179]
Dear contributors,

would you be willing to fill in a short 5-10 min survey (https://forms.gle/F3YwtLVKtk47yVhC9) about energy-efficient mobile development practices in the context of my master thesis? It's about raising awareness of software energy practices and about introducing a new open-source tool for helping in that regard. Your input would be greatly appreciated. Thanks a lot!

Ricardo Morais.

**Comment by k3b** [comment]
done:

What i am missing in the survey: "do you want to use LeafactorCI ": only yes or no is accepted. there is no way to first read about it and decide later to first read about the background i found out later by reading "https://luiscruz.github.io/papers/cruz2017performance.pdf", to experiment a litte with the gradle-plugin, ....

Therefore i answered with "do you want to use LeafactorCI = NO" without knowing if i will try it or not and learned after that what is really behind this survey.

What is missing in "https://luiscruz.github.io/papers/cruz2017performance.pdf" is how many hours per day is the app running? If an app runs 1 minute per day and you make that app 50% more energy efficient it will not save you much in total.

In my gallery app the performance critical parts (and probaly energy-costs) are: 

* generate thumbnail images (miniature-images in gallery view) of high-res images  using a limited cache of 50 MB.
* converting offline-compact-vector map data to zoom-factor-specific jpg map-tiles using a limited cache of 50 MB.

I saw that somebody created a fork of my app and created a branch with instrumentatin tests https://github.com/junior291492659/APhotoManager/tree/instrumented-version-0.6.4.180314.

Was that you?

**Comment by moraispgsi** [comment]
Thanks for taking the time with the survey, I can see that this is a topic that interests you. Yes, you are definitely right, I will be restructuring the survey, this was the first run of it and I can see that some things lead to bad user interaction. You are completely right in your assessment, the energy savings can only be accounted for while the app is being executed or running in the background. The fork was not done by me, must have been another person.
