### ISSUE TITLE
Compatibility with android-5 and android-6

### ISSUE THREAD

**Issue by k3b** [k3b/APhotoManager#18]
I only have an android-4.2-tablet and an android-4.4.2 cellphone. 

Is there somebody out there who can confirm that the app work for android-5.x and android-6, too ?

**Comment by iainnicol** [comment]
Works for me on an Android 5.1 phone, although I haven't been using it long.  Of course, Android 6 changes how permissions work a bit, and unfortunately I can't test that.

**Comment by k3b** [comment]
thanks for 5.1 feedback. i tried installing 5.0 and 6.0 android emulator but the emulator does not work on my laptop

**Comment by iainnicol** [comment]
I presume it's not as simple as adding your user to the kvm group and restarting?

I'm crazy busy for the next week, but I can definitely spin up an emulator after that to try on Android 6, and shortly after that borrow a real device.

**Comment by k3b** [comment]
no more feedback after 11 months so i assume that it works with android-5 and 6.
