### ISSUE TITLE
View Sub Folders

### ISSUE THREAD

**Issue by Macro-sudo** [k3b/APhotoManager#183]
Not an actual issue but I have no idea how to view subfolders. What I mean is instead of seeing all photos in a folder. I want to see all subfolders (with their thumbnails) in a folder. I want this because I have 60k+ photos and alot of subfolders.

Been looking but I can't find this option.

**Comment by k3b** [comment]
Closed as duplicate of #85

I have not found am easy-to-implement-solutionm for this yet.

I am using the "Folder-Picker" to navigate through the directories
