### ISSUE TITLE
𝑼𝒑𝒅𝒂𝒕𝒆 𝒇𝒐𝒓 𝑨𝒏𝒅𝒓𝒐𝒊𝒅 10

### ISSUE THREAD

**Issue by shouyou10** [k3b/APhotoManager#187]
𝑊𝑖𝑙𝑙 𝑖𝑡 𝑏𝑒 𝑝𝑜𝑠𝑠𝑖𝑏𝑙𝑒 𝑡𝑜 𝑝𝑟𝑜𝑣𝑖𝑑𝑒 𝑎𝑛 𝑢𝑝𝑑𝑎𝑡𝑒 𝑜𝑓 𝑡ℎ𝑖𝑠 𝑢𝑝 𝑓𝑜𝑟 𝑢𝑠𝑒𝑟𝑠 𝑟𝑢𝑛𝑛𝑖𝑛𝑔 𝑎𝑛𝑑𝑟𝑜𝑖𝑑 10 𝑜𝑟 ℎ𝑖𝑔ℎ𝑒𝑟.

**Comment by k3b** [comment]
closed as dulicate of #155
