### ISSUE TITLE
Private Image Setting

### ISSUE THREAD

**Issue by DelterEcho** [k3b/APhotoManager#188]
When setting pictures as private, I'm unable to find any of them afterwards. Is there a dedicated spot they would have ended up in the files?

**Comment by DelterEcho** [comment]
![Screenshot_20210201-094652](https://user-images.githubusercontent.com/78365869/106474355-d7881080-6472-11eb-9a21-a45584b7a45f.png)
It is the option here between public and private image.

**Comment by DelterEcho** [comment]
Using an external File Manager app, I found the folder of the hidden images as well as the images themselves, but since my phone does not come with a built in file manager capable of finding hidden images, a warning for the private image setting would be appreciated.

**Comment by DelterEcho** [comment]
Using an external File Manager app, I found the folder of the hidden images as well as the images themselves, but since my phone does not come with a built in file manager capable of finding hidden images, a warning for the private image setting would be appreciated. I still cannot find out how to un-Private these images, as I now cannot interact with them through any means, and the file manager where I can see the images does not have any options.

**Comment by k3b** [comment]
there is a checkbox "see private images" in menu ["filter"](https://github.com/k3b/APhotoManager/wiki/Filter-View): if checked "prvate images" will be visible.
