### ISSUE TITLE
Translation with longer texts may break Layout

### ISSUE THREAD

**Issue by k3b** [k3b/APhotoManager#28]
Since other languages sometimes need longer texts than english/german-s on "small screen devices" some longer texts donot fit onto the screen :-(

Found so far
- French: Filter - "Chemin d'accés" (eng Path) not enough place to enter the path
  - ? replace "Chemin d'accés" with "Fichier" (eng file)

**Comment by Tuuux** [comment]
May be use 2 lines one for the Title , and one for the Path text component.
Width is very expensive on small device, if you have a scroll bar height is very un expensive.
That will permit every future Language integration without any major change.

Just my 2 cents ...
