### ISSUE TITLE
crashes on media-scanner with a NPE

### ISSUE THREAD

**Issue by emdete** [k3b/APhotoManager#33]
this error is reproduceable and happens every time i start the scanner:

02-29 20:39:50.607 E/k3bFoto (28323): Caused by: java.lang.NullPointerException: Attempt to get length of null array
02-29 20:39:50.607 E/k3bFoto (28323): 	at de.k3b.android.util.RecursiveMediaScanner.scanDirOrFile(RecursiveMediaScanner.java:80)
02-29 20:39:50.607 E/k3bFoto (28323): 	at de.k3b.android.util.RecursiveMediaScanner.scanDirOrFile(RecursiveMediaScanner.java:93)
02-29 20:39:50.607 E/k3bFoto (28323): 	at de.k3b.android.util.RecursiveMediaScanner.scanDirOrFile(RecursiveMediaScanner.java:93)
02-29 20:39:50.607 E/k3bFoto (28323): 	at de.k3b.android.util.RecursiveMediaScanner.doInBackground(RecursiveMediaScanner.java:59)
02-29 20:39:50.607 E/k3bFoto (28323): 	at de.k3b.android.util.RecursiveMediaScanner.doInBackground(RecursiveMediaScanner.java:28)
02-29 20:39:50.607 E/k3bFoto (28323): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
02-29 20:39:50.607 E/k3bFoto (28323): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-29 20:39:50.607 E/k3bFoto (28323): 	... 4 more

**Comment by k3b** [comment]
Thanks for info. Which android version are you using? (I still have no feedback if the app works on android 6 #18  ) 

I will fix this on thursday afternoon

**Comment by k3b** [comment]
this issue should be fixed with the new fdroid release 0.4.6
