### ISSUE TITLE
Images are only shown as thumbnails

### ISSUE THREAD

**Issue by aeMKei1** [k3b/APhotoManager#35]
First of all, thank you for the good app and work you put into your projects. I'm not sure whether this is the right place to ask these questions but i couldn't find any homepage, blog or direct contact elsewhere and i'm quite new to github. By opening APhotoManager, i can see the thumbnail tiles of my images (the ones i took by myself and the ones i got sent via messengers), so the access to the storage works fine. But when i tap on a picture, instead of displaying it nothing happens. That being said, i have to mention, that i disabled all Google stuff on my phone (according to the guide on [http://www.xda-developers.com/setting-up-android-marshmallow-without-google/](http://www.xda-developers.com/setting-up-android-marshmallow-without-google/)) and replaced it with apps from the F-Droid store. My image viewer is "GLImageViewer" but it doesn't provide a neat gallery like your app. I'm guessing that i need some Google stuff to make your app work. If so, which of the services would i have to reactivate?

Kind regards
  aeMKei1

**Comment by k3b** [comment]
No google is not required to run the app.

The APhotoManager depends on android-s media database that is not always up to date. 

If you (or the messengers-app) delete or move a jpeg file the android-s media database might not have been updated yet so APhotoManager displays a cached preview image in the gallery view.

APhotoManager tries to compensate outdated android-s media database entries by updating the database if it cannot find a jpeg any more or opens a jpg file that is not in the database yet.

The internal copy/move/delete commands also update the database.

If this answers your question please close this ticket.

**Comment by aeMKei1** [comment]
Thanks for the fast reply, so i deleted one of the pictures and i got the notification, that the media database has been updated. But the problem remains the same, i can tap on a thumbnail, it flashes blue but it won't show the picture full screen :(

**Comment by aeMKei1** [comment]
The problem was resolved, the privacy impact settings were suppressing the app to work fine. I changed that and now it works like a charm. Thank you for your kind support.
- aeMKei1

**Comment by k3b** [comment]
thanks for updating the ticket.
