### ISSUE TITLE
Support for ".nomedia" folder. Avoid bloated mediadb and crash when adding to mediadb

### ISSUE THREAD

**Issue by k3b** [k3b/APhotoManager#36]
APhotoManager ver 0.4.6 and below does not obeye ".nomedia" folder so it adds photos from ".nomedia" folder to database.

A Crash in ver 0.4.6 ist reproducable this way: When opening a photo by *file-path* APhotoManager translates the path to a *content-uri*.

If the photo is not in found in the media database APhotoManager  starts the media scanner to add the unknown file(s). After scan has finished the photo is opend without checks.

If the photo is in a ".nomedia" folder (or in bluetooth download) the scanner does not add the photo so after scanner has finished the photo is not in the media database.

**Comment by k3b** [comment]
There is more work than fixing the crash for this to complete:

The old APhotoManager completely depends on the media database to show photos

* If APhotoManager is invoked with a file uri this uri is coverted to media-db-content: uri.
* If the file is not found in the media-db it is added.
* if files are copied/moved/deleted the media-db is also updated.

Neccessary changes:

* When obeying the ".nomedia" indicator APhotoManager is not allowed to add photos from these directories to the media db.
* GalleryView and PhotoDetailView must learn to use either media-db-data or (new) list of local files.
* filtering/sorting does not work without database.
* when files are copied/moved/deleted the media-db update is different depending on source-directory is (not) ".nomedia" and destination-directory is (not) ".nomedia" 

There is also code neccessary to remove files from  ".nomedia" folders from the media-db if APhotoManager-ver 0.4.6 and below has been run before.

**Comment by kodeblacc** [comment]
This issue is still happening, even in the latest release of the software and logcat doesn't reveal the problem.

It is reproducible with Dir File Manager and OI file manager
