### ISSUE TITLE
Use higher initial quality when displaying images in imageview

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#39]
I was looking for a replacement app for Google's photo viewer and got to this viewer via F-Droid. I have couple of remarks, one of which is the following:

On my phone, when viewing horizontal pictures 'full screen', the quality is *ok*. Yet when viewing vertical images one can clearly see that images are compressed. Only when you zoom in an image, it will display full quality.
I understand this has to do with speed, but I would expect that if an image is open for a second or so, it will load the full-quality display, both for vertical & horizontal images.

**Comment by k3b** [comment]
APhotoManager 0.5.1 will get a new setting where you can tweak this:

* [#53](https://github.com/k3b/APhotoManager/issues/53) performance/quality/thumbnail optimisation for [Image-View](Image-View) (improving [#10](https://github.com/k3b/APhotoManager/issues/10))
	* There is a new setting **Big photo width/height** optimisation for [Image-View](Image-View) 
	* Loading [#10 high resolution photos](https://github.com/k3b/APhotoManager/issues/10) into [Image-View](Image-View) may need up to 1,5 seconds thus preventing fast swiping through the images.
	* APhotoManager can load precalculated downscaled mini-versions (a. k. a. thumbnails) which is much faster (< 0.1 seconds) so swiping is possible again.
	* If the photo is bigger than **Big-photo-width-height-value** then it uses thumbnails to allow fast swiping.
	* Thumbnails means memoryefficient, fast, but lower-quality.
	* As soon as you zoom the full resolution image is loaded.

**Comment by keunes** [comment]
Curious to see how it works out in practice, don't fully understand (yet) what you wrote above.

> As soon as you zoom the full resolution image is loaded.

Isn't that the current behaviour?

> There is a new setting Big photo width/height optimisation for Image-View

Instead of introducing a new setting, isn't it possible to keep the thumbnails preloaded, but load a higher quality as soon as that image is in the view for a second? That way fast swiping is still always possible but no active user action is required to get a better picture.

**Comment by k3b** [comment]
> >    As soon as you zoom the full resolution image is loaded.

> Isn't that the current behaviour?

correct

---

> ... pre-loading thumbnails, only to load a higher quality with a delay of (half) a second ....

that could become an addon but it is much more complicated to implement.

------

> Instead of introducing a new setting,...

I have an android-4.2 tablet with more than 16000 photos. 95% of the photos have a size of 1024x768 so these can be displayed in detailview without thumbnails so this additional setting is a vast improvement as thumbnail space is saved (at least for me)

**Comment by k3b** [comment]
Unfortunately my 95% optimisation in the previous  message did not work as expected because the gallery-view produced the thumbnails anyway. So i decided redesign thumbnails.

In the current v0.5.1 developper branch i have [#54](https://github.com/k3b/APhotoManager/issues/54) replaced android-s mediaDB-thumbnails with Sergey Tarasevich's  Android-Universal-Image-Loader https://github.com/nostra13/Android-Universal-Image-Loader.

So the big-image-thumbnails will have a better quality now.

**Comment by k3b** [comment]
tomorow-s 0.5.1 release should have solved this. If not we have to reopen this ticket.
