### ISSUE TITLE
Tap to hide overlay action bar; remove setting

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#40]
I was looking for a replacement app for Google's photo viewer and got to this viewer via F-Droid. I have couple of remarks, one of which is the following:

One can set the number of miliseconds that the overlay action bar is displayed. For the sake of an easy user interface, I would:
- get rid of that setting (this is simply one of those things that should 'just work', the current setting IMHO is just fine)
- make the bar hide/display if one taps on a picture (this works similarly in many other apps; start display on tap already works)

Also, it would be nice if the overlay action bar would keep its state (hidden) if one swipes from one full image to the next. Often I don't need the tools when just flicking through my pictures (when showing them to friends & family). And if I *do* need it, I tap on the picture (like described above).

**Comment by keunes** [comment]
Related to this: the action bar should be kept longer if the overflow menu is opened. Maybe it shouldn't even be closed automatically at all.

**Comment by k3b** [comment]
i need this setting because i personally donot want to hide the actionbar (value=0). I just added this setting because other users asked me to add it

**Comment by keunes** [comment]
May I suggest to reopen this and change my request to:
make the bar hide/display if one taps on a picture (this works similarly in many other apps; start display on tap already works) if hide action bar value != 0

Also the following suggestions still stands in any situation (or should I make separate issues, esp. given the little time you have available?):
would be nice if the overlay action bar would keep its state (hidden) if one swipes from one full image to the next
the action bar should not closed automatically if the overflow menu is opened
