### ISSUE TITLE
Use folder tiles rather than complex folder picker dialog

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#41]
I was looking for a replacement app for Google's photo viewer and got to this viewer via F-Droid. I have couple of remarks, one of which is the following:

When first opening the app, one gets a whole bunch of photos. Screenshots, downloads, WhatsApp images and your own photo's are all displayed together. It would be nice if instead an overview of the folders would be displayed. For a new user, this is far more welcoming.

Additionally, when introducing the folder tiles, the (forgive my harsh wording) ugly & complicated folder picker might be removed. Or at least I don't have to use it.

**Comment by k3b** [comment]
I agree that it is confusing for a novice user to see all photos together in the gallery view without knowing the folder-picker/map-picker or filter.

     > It would be nice if [...] an overview of the folders would be displayed. 

Thats what the stock android gallery is doing. However if you have more than 1000 different folders with images it is difficuilt to find the folder or picture you are looking for. This was one of 2 reasons why i decided to create my own photo gallery app.

Do you have an idea how the app can be made easier for novice users without sacrifying the powerfull filter?

**Comment by keunes** [comment]
> Do you have an idea how the app can be made easier for novice users without sacrifying the powerfull filter?

Well, the powerful filter can still work on top of a system of folder display, right? Actually it might be beneficial for filtering:
- the 'select folder' icon in the action bar (on my 5-inch screen phone) can be replaced with a 'filter' icon; 'select folder' can be placed in the overflow menu
- always display folders and images that are present in the current folder
- when a filter is applied, display folders that contain photos that fall under the selection
- optionally: introduce 'folder/image' toggle or setting (so that users can choose whether images should be 'grouped' into their folders)

**Comment by k3b** [comment]
Is there somebody out there who wants to implement this?

**Comment by keunes** [comment]
If only I had the skills ^^
