### ISSUE TITLE
FR: Setting to not display image names in overlay

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#42]
I was looking for a replacement app for Google's photo viewer and got to this viewer via F-Droid. I have couple of remarks, one of which is the following:

All these photo names are pretty much the same, and all are rather pointless. It's just [a string of numbers.jpg]. I'd rather remove that and focus more on the image itself; that gives me far more information.

This overlay would be useful however for folder tiles.

**Comment by k3b** [comment]
On my device I always rename files to something more meaningfull. So for me they make sense .....

**Comment by keunes** [comment]
Get it. May I then suggest to reopen this issue and change the request to implement a setting for this?
