### ISSUE TITLE
Empty "Select Directory Folder" dialog?

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#44]
Dunno what the dialog is supposed to do, but for me it's rather pointless. It just doesn't display anything ;)

![screenshot_2016-05-15-11-34-21](https://cloud.githubusercontent.com/assets/11229646/15273188/3b811374-1a91-11e6-90dc-f2a5d7fa318c.png)

My device: Fairphone 2, Android 5.1. APM v. 0.4.6.160304

**Comment by k3b** [comment]
This bug is related to #36 and alread fixed in unreleased 0.4.7 development branch

**Comment by k3b** [comment]
This applies to copyTo/moveTo/scanner dir picker after navigating picker to root-directory.

**Comment by keunes** [comment]
Wouldn't guess it is related to .nomedia but trust you on it ;)

**Comment by k3b** [comment]
you are right: it was introduced in #33 "duplicate media entries via symlinks" in 0.4.6 (not in #36 ".nomedia"). I fixed the comment above.
