### ISSUE TITLE
Tile view not updated after deleting file

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#45]
When deleting a file from the full image screen, the tile overview doesn't get updated. When you then tap on an image, you get the 'wrong' image displayed. In other words: the miniature image probably isn't correct.

Fairphone 2, Android 5.1, APM 0.4.6.160304

**Comment by k3b** [comment]
This happens in ".nomedia" folders where the mediadb was not updated and therefore the gui is not updated. Should be fixed with #36
