### ISSUE TITLE
Remove 'settings' (and 'about') from full-image-view menu

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#47]
I would remove 'Settings' and 'About' as they are not specifically related to the image that one is viewing at that particular moment. Removing them IMHO improves the user experience. (also because the overflow menu is rather crowded).

**Comment by k3b** [comment]
I agree that "image detail view" is overcrowded.

But since "image detail view" can be invoked without the "gallery view" the menu should be reorganized with submenues.

**Comment by keunes** [comment]
I can imagine in that situation you want to keep 'about'. Yet I think the chance that you want to change the settings is very low if you're just watching one particular image (which is the case if you opened that image via your filesystem or another app).

**Comment by keunes** [comment]
In any case, whether you want to get rid of the 'settings' or want to reorganise stuff, the label probably shouldn't be 'won't fix' ;)

**Comment by k3b** [comment]
Implemented #52 so "Unimportant" menue are moved to the "more" submenue
