### ISSUE TITLE
Add button to clear filter settings 

### ISSUE THREAD

**Issue by HoWilgh** [k3b/APhotoManager#51]
Add a button to clear the current filter settings and show that a filter is active.

**Comment by k3b** [comment]
From usability point of view thats a good idea. 

* Currently the filter dialog already has "clear" button. 
* On small screens (smartphone) there is no extra room for an additional button in the actionbar.
* The actionbar-menü already has too many menu items.

Would it solve this issue if the "Filter" menu entry becomes "Filter (active)" if filter is not empty?

**Comment by HoWilgh** [comment]
"Filter (active)"
yes that would help in a first place. For me it was not obvious when I first used the filter that I cant change the folder. Maybe you can somehow use colors in the UI to emphasize that there is still a filter active.

**Comment by keunes** [comment]
> For me it was not obvious when I first used the filter that I cant change the folder

Can imagine that happens. If #41 gets introduced, the filter icon in the action bar can also serve as an indicator. (3 taps needed to clear: 1 open filter view 2 clear 3 go back)

> Would it solve this issue if the "Filter" menu entry becomes "Filter (active)" if filter is not empty?

I think that would help but still be insufficient, it's still rather much hidden away.

> Currently the filter dialog already has "clear" button.

It currently says 'Delete'; maybe this can be changed into 'Reset'
