### ISSUE TITLE
New thumbnail implementation

### ISSUE THREAD

**Issue by k3b** [k3b/APhotoManager#54]
Goal: replace thumbnail display from android-s internal implementatation with external lib

**Comment by HoWilgh** [comment]
Is it possible to put the thumbnails of 'APhotoManager' on the sdcard?

**Comment by k3b** [comment]
yes via Settings/Photos/Thumbnail-Folder but only if android allows write access to sdcard

**Comment by HoWilgh** [comment]
I know this option but have not been able to find the correct path to enter there. I use Android-6.1 and do have to use Storage Access Framework (SAF) to write on the sd-Card. But with SAF I do not see any path information I can select. I guess this has to be provided by the app.... by an folder picker supporting SAF.

**Comment by k3b** [comment]
sorry the app does not support read/write to SAF (#61) . on my android-7.1 i used the option to make the sd-card part of the internal memory so every android app with write permisson can use the memory via file system.

If you know how to fix this merge-requests on the master branch are welcome
