### ISSUE TITLE
Incomplete / blurry map after zooming

### ISSUE THREAD

**Issue by Basti1512** [k3b/APhotoManager#57]
### Expected behavior

After zooming the map should complete and clearly visible. 

### Actual behavior

After zooming the map is updated only partially (some parts remain empty, other parts are blurred)

### Environment

* Android Version (i.e. 5.1):
  * 6.0.1
* [A Photo Manager Version](https://github.com/k3b/APhotoManager/releases) (i.e. 0.4.6.160304) :
  * 0.5.2.160726
* Affected Module:
	* [ ] [Gallery-View](https://github.com/k3b/APhotoManager/wiki/Gallery-View)
	* [x] [Geographic-Map](https://github.com/k3b/APhotoManager/wiki/geographic-map)
	* [ ] [Image-View](https://github.com/k3b/APhotoManager/wiki/Image-View)
	* [ ] [Filtering](https://github.com/k3b/APhotoManager/wiki/Filter-View)
	* [ ] [Folder-Picker](https://github.com/k3b/APhotoManager/wiki/Folder-Picker)
	* [ ] [Settings](https://github.com/k3b/APhotoManager/wiki/settings)
	* [ ] [Intent API](https://github.com/k3b/APhotoManager/wiki/intentapi)

**Comment by k3b** [comment]
Thanks for feedback.

I am afraid, that this problem is outside of my controll.

I have the same problems when the detailed map fragments are not in local file cache and 
there are problems to download them from internet. (i.e. bad internet connection to openstreetmap map download server)

If the more detailed map-tile is not available, the osmdroid-lib tries to compensate by zooming a less detailed tile which becomes blured)

**Comment by Basti1512** [comment]
I understand. But I'm connected via 50MBit/s to the internet. Maybe the reason is a slow openstreetmap download server?!

Anyway: is there a way to force an update of the local map data / cache?

**Comment by k3b** [comment]
if there is too much traffic on the openstreetmap download server you will not get the map data. forcing a cache reload will make the situation more worse. 

APhotoManager uses the [osmdroid library](https://github.com/osmdroid/osmdroid) for the mapdisplay. this lib should handle the download caching/refreshing. I donot know how this works- i am just using it.

Is it ok to close this ticket for now? Solving this is not under my control
