### ISSUE TITLE
map view: add "longpress context menu" "open Imagage"

### ISSUE THREAD

**Issue by Kratsac** [k3b/APhotoManager#63]
### Expected behavior
In map view, show amount of thumbnails according to numbers inside of a clicked marker. When clicking a marker, show image in full size. 

### Actual behavior
Only one thumbnail is shown. When clicking it, it dissapears and nothing happens. 
...

### Environment

* Android Version 5.1
  * ...
* [A Photo Manager Version i.e. 0.5.2

**Comment by k3b** [comment]
I can add "open Imagage" to the "longpress context menu"

Current workaround "longpress" on the marker and select either 

* "open in new gallery" to get all images or
* "zoom to fit" to zoom the map to a more detailed level.
