### ISSUE TITLE
Option to remember photo editor

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#64]
There's only one photo editor I use ([Snapseed](https://play.google.com/store/apps/details?id=com.niksoftware.snapseed)), but every time I want to edit a photo APM presents me with a choice for a photo manager. It would be great if (as in other apps) one could select 'only now' or 'always'

**Comment by k3b** [comment]
This makes sense if you always use the same editor. but once you have choosen "always" you cannot get back the chooser without uninstalling. thats why i decedided to always present the chooser

**Comment by keunes** [comment]
> This makes sense if you always use the same editor.

I know you made this thing for yourself, but the above would be the case for most people ;)

> once you have choosen "always" you cannot get back the chooser without uninstalling

This is not true; see https://github.com/arpitkh96/AmazeFileManager/issues/316

**Comment by keunes** [comment]
@k3b Would you please reconsider, given the fact that it actually _is_ possible to reset these settings without having to reinstall the app. Current situation (IMHO) really is a bummer for usability.
