### ISSUE TITLE
Show in new gallery

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#65]
"From imageDetail-view you can open a new gallery view" it was answered upon my question in the translation system.
Just tried it in the app, but don't really see it's purpose. You can only have one gallery open at a time, no (it's not that there's two or more tabs that you can have different galleries open with).

Can you explain? :)

**Comment by k3b** [comment]
i implemented it for this usecase:

* whatsap - > open image -> open a new gallery view to see what else is in the whatsapp folder

If you open the imageview from a filemanager there is no open gallery below so without "Show in new gallery" you have no way to see what else is there.

**Comment by keunes** [comment]
@k3b Did you see my pull request? It solves the still current unclarity described in this issue.
