### ISSUE TITLE
Difference "sort_by_xxx" and "sort_order_xxx"

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#67]
There's a long list of 'sorting' strings. What's the difference between "sort_by_xxx" and "sort_order_xxx"?

Seems to me like they can/should be merged? In version 0.5.2 only "sort_by_xxx" seems to be used?

 +	<string name="sort_by_date">Date</string>
 +	<string name="sort_by_folder">Folder</string>
 +	<string name="sort_by_name">Name</string>
 +	<string name="sort_by_name_len">Length</string>
 +	<string name="sort_by_none">Unsorted</string>
 +	<string name="sort_by_place">Place</string>
 +	<string name="sort_menu_title">Sort</string>
 +	<string name="sort_order_Date_Ascending">Date ascending</string>
 +	<string name="sort_order_Date_Descending">Date descending</string>
 +	<string name="sort_order_Name_Ascending">Name ascending</string>
 +	<string name="sort_order_Name_Descending">Name descending</string>
 +	<string name="sort_order_Name_length_Ascending">Name-length ascending</string>
 +	<string name="sort_order_Name_length_Descending">Name-length descending</string>

**Comment by k3b** [comment]
thanks.
you found dead code that i forgot to remove. The "XXX ascending" and "XXX descending" text-s are not used any more. I will delete them from source code
