### ISSUE TITLE
Use settings_title for viewer title, edit section title

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#68]
Currently, the top bar in the settings view always shows "Settings" whilst settings_title 
- rename 'settings_title' to 'settings' (for use in the top menu bar & all overflow menus)
- introduce 'settings_group_general_title' (for use in the settings view as the first group header; it should be 'General' rather than 'Settings', as with the current state the sub-heading is exactly the same as the view title)

I can do a PR, but would first like to have my current one (for strings) accepted (to avoid conflicts etc).

Files in which 'settings_title' should be replaced by 'settings':
- APhotoManager/app/src/main/res/values/strings.xml
- APhotoManager/app/src/main/res/menu/menu_gallery_filter.xml
- APhotoManager/app/src/main/res/menu/menu_map_geo_picker.xml
- APhotoManager/app/src/main/res/menu/menu_gallery_non_multiselect.xml
- APhotoManager/app/src/main/res/menu/menu_image_detail.xml
- APhotoManager/app/src/main/res/xml/preferences.xml

**Comment by k3b** [comment]
It makes sensse to intorduce settings-subheader "Settings General" as soon a there to many settings. with the current version i sea no benefit yet.

**Comment by keunes** [comment]
> with the current version i sea no benefit yet

You know that the 'Settings' view of the app already has two sub-headings, right? 1) "Settings" and 2) "Diagnostics". So I would argue already in this version there is a benefit.

![screenshot_2016-09-10-20-27-48](https://cloud.githubusercontent.com/assets/11229646/18412691/967c08ae-7795-11e6-9b02-02f524d5ed26.png)

![screenshot_2016-09-10-20-29-41](https://cloud.githubusercontent.com/assets/11229646/18412692/9db17dde-7795-11e6-9ce5-f03ee3db919d.png)
