### ISSUE TITLE
Differentiate between 'set geo' and 'change geo'

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#69]
As per the question & answer in https://crowdin.com/translate/androFotoFinder/1/en-nl#85:

It would be useful if a differentiation would be made between 'set' and 'change' geo.

This is a low-importance enhancement request :)

**Comment by k3b** [comment]
What is the benefit of differentiation?

How would you hande mulitiselection "change geo." where all selected photos get the same new geo
and some have geo and some hove no geo?

**Comment by keunes** [comment]
As you said "yes it would be usefull to have two different menu texts" I didn't bother to explain the benefit ;)

It may be beneficial to the user as it indicates whether a particular image already has a geo-location set: if there already is a geolocation the user may decide to overwrite but at least they know they will be overwriting (lower chance to do so accidentally).

Handling multi-selection: first thing to note is that this is just a change on the User Interface: the actual technical action of the button remains the same in both cases (I assume). Concerning the labelling: easy way would be to always display "Set/Change geo" (or "Apply geo") when multiselect is active, more complicated way would be to see if all images have (or not) a geo and adjust the label accordingly (set; change; set/change).
