### ISSUE TITLE
APM crashes when attempting to view details of whatsapp image

### ISSUE THREAD

**Issue by keunes** [k3b/APhotoManager#71]
To reproduce:
- in Whatsapp, open a picture sb sent you ('view in gallery')
- choose APM if not the standard to view the image
- tap the overflow menu, tap more, tap 'Details' and APM will crash

**Comment by k3b** [comment]
@keunes

I just tested: On my android-4.4 i have no problems opening a received picture from whatsapp with apm-0.5.2.

to analyse:

* start apm
* go into the settings menue
* enable all checkboxes under Diagnostics "Logcat ...."
* press "Clear LogCat"
* the next crash log will be written to where "Errorlog folder" points 
* close APM
* let APM crash again
* The "Errorlog folder"  should contain a new file with the crash report
* attach the latest errorlog to this ticket.

**Comment by keunes** [comment]
done: [androFotofinder.logcat-20160929-221159.txt](https://github.com/k3b/APhotoManager/files/501812/androFotofinder.logcat-20160929-221159.txt)

**Comment by k3b** [comment]
thankyou for the error log.

apm tries to read exif data on a photo that has no exif infos.

The bug will be fixed with the next release.
