### ISSUE TITLE
Android-6/CM13 rooted: How can I grant write&delete access ?

### ISSUE THREAD

**Issue by herrdeh** [k3b/APhotoManager#80]
I can neither copy, nor delete any photo from within this app, neither from the external, not the internal SD card. What can I do?

I'm using CM13 (Android 6), the phone is rooted.

**Comment by k3b** [comment]
Unfortunatly i only have a android 4.4 and an android-4.2 device and no CM so i cannot help you.

I assume this issue is realated to #61 .  May be community can help.

**Comment by k3b** [comment]
closed as duplicate of #95
