### ISSUE TITLE
Too many pictures listed (not only subdirectories)

### ISSUE THREAD

**Issue by Zahnstocher** [k3b/APhotoManager#82]
If a folder is selected, only its content and the content of the subdirectories should be shown.

For example, following directory structure:
/storage/emulated/0/files/
/storage/emulated/0/files/a/
/storage/emulated/0/files/b/
/storage/emulated/0/files2/

If /storage/emulated/0/files is picked, only the images in the following directories should be listed:
/storage/emulated/0/files/
/storage/emulated/0/files/a/
/storage/emulated/0/files/b/

But also the images inside /storage/emulated/0/files2/ are listed, which is not a subdirectory of /storage/emulated/0/files/

logcat shows:
> k3bFoto: FotoGalleryActivity.navigateTo /storage/emulated/0/files from /storage/emulated/0

But addWhereDirectoryPath just appends a "%" at the end (a slash is missing?):
> addWhere(FotoSql.SQL_COL_PATH + " like ?", selectedAbsolutePath + "%")

https://github.com/k3b/APhotoManager/blob/8feda490716f550bc427a65d18257071d17374d0/app/src/main/java/de/k3b/android/androFotoFinder/queries/FotoSql.java#L389

I think it should be "/%" or something like that?
So that only subdirectories are selected?

Not sure, if I'm looking at the right code...

**Comment by k3b** [comment]
the problem still exists in 0.6.0

**Comment by k3b** [comment]
fix should be available in 0.6.1
