### ISSUE TITLE
Thumbnails are huge (same as original image)

### ISSUE THREAD

**Issue by Zahnstocher** [k3b/APhotoManager#83]
My .thumbCache folder is several GB big.
The files in this directory are the original images (same size and MD5 sum), but with different file name.
Version 0.5.5.161220

**Comment by k3b** [comment]
confirm: the problem exists on my android-4.2 in app version0.6.0

**Comment by k3b** [comment]
there seem to be more problems with the image cache

* setting  .thumbCache folder does not work
* setting image below treshold should not use the thumb cache at all

**Comment by k3b** [comment]
I tried to make the cached items smaller but that mades scrolling much slowe
in de.k3b.android.androFotoFinder.ThumbNailUtils.init(...)

        ImageLoaderConfiguration.Builder config = new ImageLoaderConfiguration.Builder(context);
        ...
        config.diskCacheExtraOptions(Global.imageDetailThumbnailIfBiggerThan, Global.imageDetailThumbnailIfBiggerThan, null);
        ...
        ImageLoader.getInstance().init(config.build());

I did small extra optimiszion my excluding small images from cache in gallery view.

@Zahnstocher: do you know to make the files in the cache smaller without performance peelties?

**Comment by maszek** [comment]
As a friendly reminder, I have this issue too on Nandroid 7.0. 

The .thumbcache folder uses nearly half a Gb storage for 185 files:
![screenshot_20170805-203251](https://user-images.githubusercontent.com/990963/28997815-0bc151a6-7a1e-11e7-94a1-b4890021e699.jpg)

Top 10 of larges files looks like this:
![screenshot_20170805-203314](https://user-images.githubusercontent.com/990963/28997816-0bc4b4d6-7a1e-11e7-82ce-e6d3f0fc4332.jpg)

**Comment by k3b** [comment]
As a workaround until this is fixed you can delete the thumbnail folder. It will be regenerated.

May be this is helpfull: https://github.com/nostra13/Android-Universal-Image-Loader/issues/991

**Comment by k3b** [comment]
I have added a hardcoded limit of 50MB/1024 cache files.

Should be available with version 0.6.2

**Comment by k3b** [comment]
will go into hotfix v0.6.1.170816 (32)
