### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [k3b/APhotoManager#97]
Hi @k3b 

I found [this app](https://play.google.com/store/apps/details?id=co.mau) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app.

**Comment by k3b** [comment]
Thanks for the info. I have also updated the warning on the homepage about potentially unwanted side effects.

**Comment by Poussinou** [comment]
Many apps are published without authorization or respect of the free licenses on the Play Store... like the ones you mention.

**Comment by k3b** [comment]
i have just send this text to google via 

* https://support.google.com/googleplay/android-developer/contact/takedown?hl=en

as "Unlawful activities"

copywright infringement: co.mau is based on gpl-v3 Software https://github.com/k3b/APhotoManager/ where Icon was changed and Advertising was added. No source code of the changes is provided and 
the app is probabliy linked against no free Software. I am the author of APhotoManager and 
i have not issued any non-gpl licese to the author of co.mau

lets see what happens

**Comment by Poussinou** [comment]
It will be interesting for sure.

**Comment by Poussinou** [comment]
@k3b I'll close this issue now since the app has been removed, but feel free to reopen it if you find another copy, and please copy-paste the link of the fake app here so that I can track the fake developper

Thanks for tacking action :)

**Comment by k3b** [comment]
thanks for taking care
